workspace:
  base: /go/src
  path: github.com/appleboy/drone-scp

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  test:
    image: appleboy/golang-testing:1.10.0
    pull: true
    secrets: [ codecov_token ]
    commands:
      - make ssh-server
      - make vet
      - make lint
      - make fmt-check
      - coverage all
      - make coverage

  build_linux_amd64:
    image: appleboy/golang-testing:1.10.0
    pull: true
    group: build
    commands:
      - make build_linux_amd64

  build_linux_arm64:
    image: appleboy/golang-testing:1.10.0
    pull: true
    group: build
    commands:
      - make build_linux_arm64

  build_linux_arm:
    image: appleboy/golang-testing:1.10.0
    pull: true
    group: build
    commands:
      - make build_linux_arm

  release:
    image: appleboy/golang-testing:1.10.0
    pull: true
    commands:
      - make release
    when:
      event: [ tag ]
      local: false

  publish_linux_amd64:
    image: plugins/docker:17.05
    pull: true
    secrets: [ docker_username, docker_password ]
    group: release
    repo: ${DRONE_REPO}
    auto_tag: true
    dockerfile: Dockerfile
    when:
      event: [ push, tag ]
      local: false

  # publish_linux_arm64:
  #   image: plugins/docker:17.05
  #   pull: true
  #   secrets: [ docker_username, docker_password ]
  #   group: release
  #   repo: ${DRONE_REPO}
  #   auto_tag: true
  #   auto_tag_suffix: arm64
  #   dockerfile: Dockerfile.arm64
  #   when:
  #     event: [ push, tag ]
  #     local: false

  # publish_linux_arm:
  #   image: plugins/docker:17.05
  #   pull: true
  #   secrets: [ docker_username, docker_password ]
  #   group: release
  #   repo: ${DRONE_REPO}
  #   auto_tag: true
  #   auto_tag_suffix: arm
  #   dockerfile: Dockerfile.arm
  #   when:
  #     event: [ push, tag ]
  #     local: false

  release_tag:
    image: plugins/github-release
    secrets: [ github_release_api_key ]
    group: release
    files:
      - dist/release/*
    when:
      event: [ tag ]
      local: false

  discord:
    image: appleboy/drone-discord
    pull: true
    secrets: [ discord_webhook_id, discord_webhook_token ]
    when:
      status: [ changed, failure ]
