workspace:
  base: /go/src
  path: github.com/appleboy/drone-scp

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  test:
    image: appleboy/golang-testing:1.9.2
    pull: true
    group: build
    secrets: [ codecov_token ]
    commands:
      - make ssh-server
      - make vet
      - make lint
      - make fmt-check
      - coverage all
      - make coverage

  build_linux_amd64:
    image: appleboy/golang-testing:1.9.2
    pull: true
    group: build
    commands:
      - make build_linux_amd64

  build_linux_i386:
    image: appleboy/golang-testing:1.9.2
    pull: true
    group: build
    commands:
      - make build_linux_i386

  build_linux_arm64:
    image: appleboy/golang-testing:1.9.2
    pull: true
    group: build
    commands:
      - make build_linux_arm64

  build_linux_arm:
    image: appleboy/golang-testing:1.9.2
    pull: true
    group: build
    commands:
      - make build_linux_arm

  release:
    image: appleboy/golang-testing:1.9.2
    pull: true
    commands:
      - make release
    when:
      event: [ tag ]
      local: false

  publish_alpine:
    image: plugins/docker
    group: release
    pull: true
    dockerfile: Dockerfile.alpine
    secrets: [ docker_username, docker_password ]
    default_tags: true
    default_suffix: alpine
    repo: ${DRONE_REPO}
    when:
      event: [ push, tag ]
      local: false

  publish_linux_amd64:
    image: plugins/docker:17.05
    pull: true
    secrets: [ docker_username, docker_password ]
    group: release
    repo: ${DRONE_REPO}
    auto_tag: true
    dockerfile: Dockerfile
    when:
      event: [ push, tag ]
      local: false

  publish_linux_i386:
    image: plugins/docker:17.05
    pull: true
    secrets: [ docker_username, docker_password ]
    group: release
    repo: ${DRONE_REPO}
    auto_tag: true
    auto_tag_suffix: i386
    dockerfile: Dockerfile.i386
    when:
      event: [ push, tag ]
      local: false

  publish_linux_arm64:
    image: plugins/docker:17.05
    pull: true
    secrets: [ docker_username, docker_password ]
    group: release
    repo: ${DRONE_REPO}
    auto_tag: true
    auto_tag_suffix: arm64
    dockerfile: Dockerfile.arm64
    when:
      event: [ push, tag ]
      local: false

  publish_linux_arm:
    image: plugins/docker:17.05
    pull: true
    secrets: [ docker_username, docker_password ]
    group: release
    repo: ${DRONE_REPO}
    auto_tag: true
    auto_tag_suffix: arm
    dockerfile: Dockerfile.arm
    when:
      event: [ push, tag ]
      local: false

  release_tag:
    image: plugins/github-release
    secrets: [ github_release_api_key ]
    group: release
    files:
      - dist/release/*
    when:
      event: [ tag ]
      local: false

  facebook:
    image: appleboy/drone-facebook
    secrets: [ fb_page_token, fb_verify_token ]
    pull: true
    to: 1234973386524610
    when:
      status: [ changed, failure ]
